name: Deploy Superset
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Копируем файл настройки на сервер
      - name: Copy docker-compose via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "~/apps/superset"

      # Заходим на сервер и запускаем
      - name: Start Containers
        uses: appleboy/ssh-action@v1.0.3
        env:
          SUPERSET_SECRET_KEY: ${{ secrets.SUPERSET_SECRET_KEY }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: SUPERSET_SECRET_KEY,POSTGRES_USER,POSTGRES_PASSWORD,POSTGRES_DB,REDIS_HOST,REDIS_PORT,REDIS_PASSWORD
          script: |
            mkdir -p ~/apps/superset
            cd ~/apps/superset
            docker compose pull
            docker compose up -d